version: 2.1

executors:
  my-exec-env:
    docker:
      - image: amazon/aws-cli

jobs:
  create-infra:
    executor: my-exec-env
    steps:
      - checkout
      - run:
          name: Create deployment infra
          command: |
            aws cloudformation create-stack --stack-name circleci-infra \
            --template-body file://infra.yml --parameters file://infra-params.json  \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
      - run: 
          name: Update deployment Stack
          command: |
            aws cloudformation update-stack --stack-name circleci-infra \
            --template-body file://infra.yml --parameters file://infra-params.json  \
            --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
          when: on_fail

workflows:
  default:
    jobs:
      - create-infra