---
- name: Update the apt repository
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install Nodejs
  become: yes
  apt:
    name: ["nodejs","npm"]
    state: latest

- name: Install Process Manager (PM2)
  become: yes
  ansible.builtin.shell: npm install pm2 -g

- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Deploy application
  become: yes
  copy:
    src: index.js
    dest: ~/web/

- name: Start the server
  become: yes
  ansible.builtin.command: pm2 start ~/web/index.js -f